[versions]
java = "21"
kotlin = "2.2.21"
asm = "9.9"

[libraries]
gson = { module = "com.google.code.gson:gson", version = "2.13.2" }
stitch = { module = "net.fabricmc:stitch", version = "0.6.2" }
tomlj = { module = "org.tomlj:tomlj", version = "1.1.1" }
asm = { module = "org.ow2.asm:asm", version.ref = "asm" }
asm-tree = { module = "org.ow2.asm:asm-tree", version.ref = "asm" }
asm-commons = { module = "org.ow2.asm:asm-commons", version.ref = "asm" }
jopt-simple = { module = "net.sf.jopt-simple:jopt-simple", version = "6.0-alpha-3" }
jimfs = { module = "com.google.jimfs:jimfs", version = "1.3.1" }
jline-terminal = { module = "org.jline:jline-terminal", version = "3.21.0" }

procyon-compilertools = { module = "org.bitbucket.mstrobel:procyon-compilertools", version = "0.6.0" }
vineflower = { module = "org.vineflower:vineflower", version = "1.11.1" }
cfr = { module = "org.benf:cfr", version = "0.152" }

[bundles]
asm = ['asm', 'asm-tree', 'asm-commons']
decompilers = ['procyon-compilertools', 'vineflower', 'cfr']

[plugins]
jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
shadow = { id = "com.gradleup.shadow", version = "9.2.2" }